#!/usr/bin/python3

import sys

from eufs_tracks.TrackGeneratorModule import EUFSTrackGenerator
from rqt_gui.main import Main

plugin = 'eufs_tracks.TrackGeneratorModule.EUFSTrackGenerator'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
